# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-18 10:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20161013_1247'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='nb_vues',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
