# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-19 14:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_article_nb_vues'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='nb_vues',
            field=models.IntegerField(default=0),
        ),
    ]
