# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-10-31 16:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_auto_20161031_1013'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='nb_vues',
        ),
    ]
