# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-10-31 16:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_remove_article_nb_vues'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='nb_vues',
            field=models.IntegerField(default=0),
        ),
    ]
